### PR TITLE
transforms and augmentation getters and setters

### PR DESCRIPTION
**Pull request by etetteh**

### CODE REVIEW

**Comment by ieee8023** [comment]
Just getting around to this now. Let's imagine how this code should work:

```python
data_aug = torchvision.transforms.Compose([
        xrv.datasets.ToPILImage(),
        torchvision.transforms.RandomAffine(45, translate=(0.15, 0.15), scale=(0.85, 1.15)),
        torchvision.transforms.ToTensor()
    ])

d_nih = xrv.datasets.NIH_Dataset(imgpath=".", data_aug=data_aug)

d_subset = xrv.datasets.SubsetDataset(d_nih, [0,1,2])

d_subset.data_aug = None

# d_nih.data_aug is still has transforms set so this assignment doesn't do anything.

d_subset2 = xrv.datasets.SubsetDataset(d_nih, [3,4,5])

# if we allowed SubsetDataset to write to wrapped d_nih it would not 
# be clear why the second SubsetDataset is modified by the first object.
```

So I think a better solution is to catch any assignment to `d_subset.data_aug` and raise an error and say that the data aug must be set on the wrapped dataset.

Possibly using `__setattr__` can raise an error if these fields are set.

**Comment by etetteh** [comment]
"assignment doesn't do anything"... the changes I made to the `SubsetDataset` function solves the issues of the `data_aug` and `transform` attributes post-assignment issues.
I am running my fork version of `torchxrayvision`, and everything works as expected
[Check this](url
Screenshot from 2021-12-25 04-43-51

[And this](Screenshot from 2021-12-25 04-55-27

Maybe, I am not really getting you.

**Comment by ieee8023** [comment]
In the second example `d_nih.data_aug` would not be empty. So for that reason I think it should throw an error when an assignment is attempted.

**Comment by etetteh** [comment]
I don't think that should be a problem. All we need is the flexibility to set the attributes of the `subset` as and when we need it. Yes, `d_nih.data_aug` won't be empty if we pre-set the attributes, but it doesn't matter, because it's the `subsets` we care about. We are not going to use `d_nih` at any point.

**Comment by ieee8023** [comment]
The issue is that setting the attribute of the subset won't modify how the samples are augmented. The data_aug field is only used when it is set on the initial dataset object.

**Pull request closed without merging**
