### PR TITLE
Updated after review, corrects small problems.

### PR DESCRIPTION
**Pull request by str4w**

### CODE REVIEW

**Comment by ieee8023** [comment]
Can you fix this merge conflict somehow? Last time I renamed the notebook in order to merge it.

**Comment by str4w** [comment]
Closed - will re-pull from upstream and try again.

**Comment by str4w** [comment]
Ok, that seems ok now thanks to the dark magic of git mergetool

**Comment by str4w** [comment]
That was painful.  Lesson learned, avoid pulling from the upstream fork  and merging jupyter notebooks through the web interface.  Pull from the upstream fork at the command line.

**Pull request merged**
